queue_rules:
  - name: default
    conditions:
      # Conditions to get out of the queue (= merged)
      - check-success=Travis CI - Pull Request
      - check-success=typesafe-cla-validator

pull_request_rules:
  - name: Merge PRs that are ready
    conditions:
      - check-success=Travis CI - Pull Request
      - check-success=typesafe-cla-validator
      - "#approved-reviews-by>=1"
      - "#review-requested=0"
      - "#changes-requested-reviews-by=0"
      - label!=status:block-merge
    actions:
      queue:
        method: merge
        name: default
